### ISSUE TITLE
Extension constantly resetting Access Token

### ISSUE THREAD

**Issue by ZakharPustovgarov** [playcanvas/vscode-extension#15]
v0.1.6 resets Access Token when i try to add it and resets it even when i try to update from v0.1.5 with valid Access Token.
v0.1.5 works fine in this regard.

**Comment by isumygin-sc** [comment]
hi, we save a token into secure storage of VS Code and clear settings, so it's not going to insecure plain text documents somewhere on filesystem. So your token is actually saved and you can use it.

**Comment by isumygin-sc** [comment]
I am going to improve this, as it seems confusing for many developers.

**Comment by ZakharPustovgarov** [comment]
Yeah, that is very confusing, but it seems to work indeed. Thanks for the explanation!

**Comment by marklundin** [comment]
When it saves, maybe you can just flash a message indicating what's happened, so the user is aware

**Comment by isumygin-sc** [comment]
the better way just to ask for it in a dialog, as for password, it's actually already there, I just need to tweak it
