### ISSUE TITLE
Bad request on save

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/vscode-extension#2]
Created a blank project, successfully added as a folder to VSCode, created a script that also appeared in Editor.

Added a line of code and saved - the change propagated to the script in Editor. Attached the script to an entity.

After that any change to script fails to save with a bad request error. Let me know, if there are some additional logs I could provide.

![image](https://github.com/playcanvas/vscode-extension/assets/5677782/73393838-5fdf-465e-a140-e9a584ff7d3c)

**Comment by friuns2** [comment]
actual error it returns
'Asset was modified by another user, please pull the latest version'

**Comment by isumygin-sc** [comment]
thanks for reporting this, we will check it this week.

**Comment by friuns2** [comment]
![image](https://github.com/playcanvas/vscode-extension/assets/16543239/e1267f31-881d-4311-a454-edfc6c7ca541)
same here can't add project

**Comment by Sandstedt** [comment]
I get the same error after saving a script-file in VS Code, and then pressing the recompile button on a entity with that script on in PlayCanvas editor. No sure if it's the same problem as you have. (uses this when adding new attributes)

**But theres a workaround:**
- Save the file in VS Code
- Click recompile in the editor
- Right click on the file in VS Code and choose, PlayCanvas: Pull latest (the file will close)
- Reopen the file

Now I can continue writing my code and save without a problem.

**Comment by isumygin-sc** [comment]
https://github.com/playcanvas/vscode-extension/pull/9 the fix
