### ISSUE TITLE
Extension is not working

### ISSUE THREAD

**Issue by ahmetfatihavci** [playcanvas/vscode-extension#21]
I’m using the latest version of the extension and Visual Studio Code. When I try ‘PlayCanvas: Add Project’, nothing happens

**Comment by willeastcott** [comment]
Latest build seems to work fine for me:

![vscodeext](https://github.com/user-attachments/assets/b5c9793a-d41c-4c67-b250-33c58734bad7)

Can you confirm:

* You correctly entered your API key when you originally installed the extension
* You actually have projects in your PlayCanvas account

**Comment by ahmetfatihavci** [comment]
I have projects on PlayCanvas. The extension was actually installed and working before. However, I revoked it yesterday and created a new token. But now, unfortunately, nothing happens when I try PlayCanvas: Add Project. I tried uninstalling and reinstalling the extension, but it didn’t work. I also tried it from the Cursor, but that didn’t work either.

**Comment by ahmetfatihavci** [comment]
![Untitled](https://github.com/user-attachments/assets/55d7da5b-84c6-4148-aaf8-ee9b5516a853)

**Comment by willeastcott** [comment]
It seems that when you uninstall the extension and reinstall it, it doesn't re-request the API key. The person that owns this repo is on vacation for another week so unfortunately, you might have to wait until he's back to get this resolved.

**Comment by dnoparker** [comment]
I have the same issue as mentioned in the previous issue post. Looking forward for this to be resolved, I have some big projects on with PlayCanvas, and having VS IDE would be amazing. Cheers!

**Comment by ahmetfatihavci** [comment]
@willeastcott thanks for helping. I hope the bug is fixed as soon as possible

**Comment by ahmetfatihavci** [comment]
@willeastcott Hello, is there any new update?

**Comment by isumygin-sc** [comment]
hello, do you see this message box after running "Add Project"? 
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/5cd3e60d-3f37-48e6-80b0-0c35b8dcacb0">

**Comment by willeastcott** [comment]
Hey @ahmetfatihavci and @dnoparker - please respond to @isumygin-sc when you get a second. We're keen to resolve this for you.

**Comment by dnoparker** [comment]
It is now working for me all of a sudden. Did you change something at the backend?

**Comment by isumygin-sc** [comment]
> Hey @isumygin-sc No, I don’t see it. I had posted a gif at the top of the page about this.

I see .. could you please send me extension logs for playcanvas extension (after reproducing the issue) ? this video explain how to get them - https://www.youtube.com/watch?v=FflD3s1aO7M

**Comment by ahmetfatihavci** [comment]
I watched the video, and since there was no error after doing ‘>PlayCanvas Add Project,’ there is unfortunately nothing related to PlayCanvas in the logs. Could you check if you have this kind of error as well? @dnoparker 
![Screen Recording 2024-11-07 at 13 45 00](https://github.com/user-attachments/assets/f1e6dc38-7d3f-46d5-b383-63e09d225f3a)

**Comment by ahmetfatihavci** [comment]
@isumygin-sc Good news! I caught this log from the developer tool.
![Screenshot 2024-11-07 at 13 51 55](https://github.com/user-attachments/assets/0705db33-7617-4d1b-9eb0-49d8085b3b3f)

**Comment by dnoparker** [comment]
I do not get any error when using 'Add Project' and the extension is now working as expected. I noticed that the extension hasn't been updated, so I am just a bit baffled that it is suddenly working haha

**Comment by isumygin-sc** [comment]
hello, thanks for providing logs! I think I fixed the issue in v0.2.1 - please update the extension

**Comment by ahmetfatihavci** [comment]
@isumygin-sc Yes, the issue has been resolved. Thank you very much!
